######################################################################
# Automatically generated by qmake (3.0) Thu Aug 27 04:24:34 2015
######################################################################

TEMPLATE = app
TARGET = todo
INCLUDEPATH += .

# Input
SOURCES += main.cpp
